sonar.projectKey=TranHuuLoiDev_KCPM
sonar.organization=TranHuuLoiDev
sonar.projectName=KCPM
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**
sonar.php.coverage.reportPaths=
sonar.sourceEncoding=UTF-8